package sd.sensecapd.webapi.model.Sensor;

/*
 * sensor measure's record
 * (retrieved from the web and saved to DB)
 * */
public class MeasureNote {
    //Unique identification, generated by database
    private int id;
    //device eui, get from MQTT Connection and saved to DB
    private String dev_eui;
    //measure id, get from MQTT Connection and saved to DB
    private int measure_id;
    //channel, get from MQTT Connection and saved to DB
    private int channel;
    //value, get from MQTT Connection and saved to DB
    private double value;
    //time stamp, get from MQTT Connection and saved to DB
    private long time;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDev_eui() {
        return dev_eui;
    }

    public void setDev_eui(String dev_eui) {
        this.dev_eui = dev_eui;
    }

    public int getMeasure_id() {
        return measure_id;
    }

    public void setMeasure_id(int measure_id) {
        this.measure_id = measure_id;
    }

    public int getChannel() {
        return channel;
    }

    public void setChannel(int channel) {
        this.channel = channel;
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }
}
