package sd.sensecapd.webapi.model.Sensor;

/*
 * sensor measure
 * (retrieved from the web and saved to DB)
 * */
public class NodeSensorMeasure {
    //Unique identification, generated by database
    private int id;
    //device eui, get from the web and saved to DB
    private String dev_eui;
    //sensor eui, get from the web and saved to DB
    private String sensor_eui;
    //measure eui, get from the web and saved to DB
    private int measure_id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDev_eui() {
        return dev_eui;
    }

    public void setDev_eui(String dev_eui) {
        this.dev_eui = dev_eui;
    }

    public String getSensor_eui() {
        return sensor_eui;
    }

    public void setSensor_eui(String sensor_eui) {
        this.sensor_eui = sensor_eui;
    }

    public int getMeasure_id() {
        return measure_id;
    }

    public void setMeasure_id(int measure_id) {
        this.measure_id = measure_id;
    }
}
